name: Check Markdown links

#
# Documentation:
# https://github.com/gaurav-nelson/github-action-markdown-link-check#how-to-use
#

on:
  push:
    branches: [main]
    paths: ["**.md"]
  pull_request:
    branches: [main]
    paths: ["**.md"]

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
